# Generated by Django 5.0.6 on 2026-03-20 07:05

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("short_description", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Full description (Markdown supported)"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="projects/covers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="completed",
                        max_length=15,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated: Python, PyTorch, …",
                        max_length=300,
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("paper_url", models.URLField(blank=True)),
                (
                    "metric_label",
                    models.CharField(
                        blank=True, help_text="e.g. Accuracy", max_length=60
                    ),
                ),
                (
                    "metric_value",
                    models.CharField(blank=True, help_text="e.g. 97.3%", max_length=30),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a related blog post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="blog.post",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
