# Generated by Django 5.0.6 on 2026-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Basanta Singh", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        default="Data Scientist · AI/ML Engineer · Educator",
                        max_length=200,
                    ),
                ),
                ("bio_short", models.TextField(help_text="2–3 sentence homepage bio")),
                (
                    "bio_long",
                    models.TextField(
                        help_text="Full about page bio (supports Markdown)"
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="core/")),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF CV for download",
                        upload_to="core/cv/",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="mailbasantasingh@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Biratnagar, Nepal", max_length=100
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
                ("orcid_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("researchgate_url", models.URLField(blank=True)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("google_analytics_id", models.CharField(blank=True, max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Profile",
                "verbose_name_plural": "Site Profile",
            },
        ),
    ]
