# Generated by Django 5.0.6 on 2026-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, help_text="e.g. CS301", max_length=20),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                            ("professional", "Professional Development"),
                        ],
                        default="undergraduate",
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                (
                    "partner_university",
                    models.CharField(
                        blank=True,
                        help_text="e.g. University of Wolverhampton, UK",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "syllabus",
                    models.TextField(
                        blank=True, help_text="Markdown list of topics covered"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="teaching/covers/"),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class e.g. fa-brain",
                        max_length=60,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, help_text="e.g. 2024–25", max_length=20
                    ),
                ),
                ("semester", models.CharField(blank=True, max_length=40)),
                ("credits", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "students_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "course_url",
                    models.URLField(
                        blank=True, help_text="External course/module page"
                    ),
                ),
                (
                    "materials_url",
                    models.URLField(
                        blank=True, help_text="Slides / GitHub / Drive link"
                    ),
                ),
                (
                    "syllabus_pdf",
                    models.FileField(blank=True, upload_to="teaching/syllabi/"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently teaching?"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-academic_year", "title"],
            },
        ),
    ]
